version: '3.8' # Updated to use condition: service_healthy

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "9880:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - node-app
    networks:
      - fullcycle-network

  node-app:
    container_name: node-app
    build:
      context: ./nodejs
      dockerfile: Dockerfile
    volumes:
      - ./nodejs:/app
      - /app/node_modules
    environment:
      - MYSQL_HOST=mdb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=nodedb
    entrypoint: ["sh", "-c", "npm install && node index.js"]
    depends_on:
      mdb:
        condition: service_healthy
    networks:
      - fullcycle-network

  mdb:
    container_name: mdb
    image: mysql:5.7
    restart: always
    command: --innodb-use-native-aio=0
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - fullcycle-network

networks:
  fullcycle-network:
    driver: bridge
