FROM ubuntu:latest


RUN apt-get update && apt-get install -y curl git


RUN curl -LO https://golang.org/dl/go1.22.4.linux-amd64.tar.gz && \
    tar -C /usr/local -xzf go1.22.4.linux-amd64.tar.gz


ENV PATH="/usr/local/go/bin:${PATH}"


WORKDIR /workspace


FROM golang:alpine AS builder

WORKDIR /app
COPY ./workspace .

RUN go mod init github.com/marcoxdd/fullcycle-docker-go
RUN go build -o main .

FROM scratch
COPY --from=builder /app/main .

ENTRYPOINT ["./main"]
